# Generated by Django 6.0.7 on 2026-07-17 06:10

import django.core.validators
import django.db.models.deletion
import django.db.models.functions.text
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProxmoxCluster',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('key', models.CharField(max_length=63, validators=[django.core.validators.RegexValidator(message='Cluster key must be lowercase and URL-safe: it may contain a-z, 0-9 and hyphens, must start with a letter or digit, and may be at most 63 characters.', regex='^[a-z0-9][a-z0-9-]{0,62}$')])),
                ('display_name', models.CharField(max_length=160)),
                ('enabled', models.BooleanField(default=True)),
                ('discovered_name', models.CharField(blank=True, max_length=255)),
                ('discovered_ca_uuid', models.CharField(blank=True, max_length=64)),
                ('discovered_ca_fingerprint', models.CharField(blank=True, max_length=200)),
                ('details', models.JSONField(blank=True, default=dict)),
            ],
            options={
                'ordering': ['key'],
                'constraints': [models.UniqueConstraint(django.db.models.functions.text.Lower('key'), name='unique_cluster_key_case_insensitive'), models.UniqueConstraint(condition=models.Q(('enabled', True)), fields=('enabled',), name='single_enabled_cluster_until_activation')],
            },
        ),
        migrations.AddField(
            model_name='proxmoxendpoint',
            name='cluster',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='endpoints', to='core.proxmoxcluster'),
        ),
        migrations.CreateModel(
            name='RuntimeConfigurationState',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.PositiveSmallIntegerField(default=1, primary_key=True, serialize=False)),
                ('bootstrap_completed', models.BooleanField(default=False)),
                ('bootstrap_completed_at', models.DateTimeField(blank=True, null=True)),
                ('bootstrap_fingerprint', models.CharField(blank=True, max_length=64)),
                ('identity_contract_version', models.PositiveSmallIntegerField(default=0)),
                ('credential_cutover_completed_at', models.DateTimeField(blank=True, null=True)),
                ('trust_cutover_completed_at', models.DateTimeField(blank=True, null=True)),
                ('details', models.JSONField(blank=True, default=dict)),
            ],
            options={
                'constraints': [models.CheckConstraint(condition=models.Q(('id', 1)), name='runtime_configuration_state_is_singleton')],
            },
        ),
    ]
