# Generated by Django 6.0.7 on 2026-07-24

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0003_cluster_retirement"),
    ]

    operations = [
        migrations.AddField(
            model_name="clusterstorage",
            name="unmanaged_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddIndex(
            model_name="clusterstorage",
            index=models.Index(
                fields=["cluster", "unmanaged_at"],
                name="core_cstorage_unmanaged_idx",
            ),
        ),
    ]
