# Generated by Django 6.0.7 on 2026-07-17 06:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_backfill_default_cluster'),
    ]

    operations = [
        migrations.CreateModel(
            name='ScanClusterObservation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('nodes_attempted', models.JSONField(blank=True, default=list)),
                ('nodes_succeeded', models.JSONField(blank=True, default=list)),
                ('errors', models.JSONField(blank=True, default=dict)),
            ],
            options={
                'ordering': ['cluster__key'],
            },
        ),
        migrations.RemoveConstraint(
            model_name='proxmoxstorageconsumer',
            name='unique_storage_expected_consumer',
        ),
        migrations.AddField(
            model_name='proxmoxstorageconsumer',
            name='cluster',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='storage_consumers', to='core.proxmoxcluster'),
        ),
        migrations.AddConstraint(
            model_name='proxmoxstorageconsumer',
            constraint=models.UniqueConstraint(fields=('storage', 'cluster', 'expected_node_name'), name='unique_storage_cluster_expected_consumer', nulls_distinct=False),
        ),
        migrations.AddField(
            model_name='scanclusterobservation',
            name='cluster',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='scan_observations', to='core.proxmoxcluster'),
        ),
        migrations.AddField(
            model_name='scanclusterobservation',
            name='scan_run',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cluster_observations', to='core.scanrun'),
        ),
        migrations.AddConstraint(
            model_name='scanclusterobservation',
            constraint=models.UniqueConstraint(fields=('scan_run', 'cluster'), name='unique_scan_cluster_observation'),
        ),
    ]
