# Generated by Django 6.0.7 on 2026-07-25 06:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_cluster_storage_unmanaged'),
    ]

    operations = [
        migrations.CreateModel(
            name='LogForwarderTransportTrust',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('mode', models.CharField(choices=[('unset', 'Not approved yet'), ('pinned', 'This certificate only'), ('ca', 'Any certificate from this issuer'), ('insecure', 'Any certificate (no verification)')], default='unset', max_length=12)),
                ('host', models.CharField(blank=True, max_length=255)),
                ('port', models.PositiveIntegerField(default=0)),
                ('certificate_pem', models.TextField(blank=True)),
                ('sha256_fingerprint', models.CharField(blank=True, max_length=64)),
                ('subject', models.CharField(blank=True, max_length=500)),
                ('issuer', models.CharField(blank=True, max_length=500)),
                ('not_after', models.DateTimeField(blank=True, null=True)),
                ('approved_at', models.DateTimeField(blank=True, null=True)),
                ('approved_by', models.CharField(blank=True, max_length=150)),
                ('last_checked_at', models.DateTimeField(blank=True, null=True)),
                ('observed_sha256_fingerprint', models.CharField(blank=True, max_length=64)),
                ('observed_subject', models.CharField(blank=True, max_length=500)),
                ('observed_not_after', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
