# Generated by Django 6.0.7 on 2026-07-17 08:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_backfill_storage_consumer_cluster'),
    ]

    operations = [
        migrations.CreateModel(
            name='ClusterCredential',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('token_id', models.CharField(max_length=255)),
                ('token_secret_sealed', models.TextField()),
                ('encryption_key_id', models.CharField(db_index=True, max_length=64)),
                ('rotated_at', models.DateTimeField(blank=True, null=True)),
                ('details', models.JSONField(blank=True, default=dict)),
                ('cluster', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='credential', to='core.proxmoxcluster')),
            ],
            options={
                'ordering': ['cluster__key'],
            },
        ),
    ]
