# Generated by Django 6.0.6 on 2026-06-30 08:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_oidcidentity'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='storagespacesnapshot',
            new_name='core_storag_storage_10c3c9_idx',
            old_name='core_storag_storage_idx',
        ),
        migrations.AlterField(
            model_name='fileinventory',
            name='classification',
            field=models.CharField(choices=[('referenced', 'Referenced'), ('likely_orphan', 'Likely orphan'), ('unknown', 'Unknown'), ('classification_blocked', 'Classification blocked'), ('trash', 'Trash'), ('infrastructure', 'Infrastructure'), ('proxmox_content', 'Proxmox content')], default='unknown', max_length=40),
        ),
    ]
