# Generated by Django 6.0.7 on 2026-07-17 08:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_cluster_credentials'),
    ]

    operations = [
        migrations.AddField(
            model_name='proxmoxendpoint',
            name='normalized_url',
            field=models.CharField(blank=True, max_length=512),
        ),
        migrations.AddConstraint(
            model_name='proxmoxendpoint',
            constraint=models.UniqueConstraint(condition=models.Q(('normalized_url', ''), _negated=True), fields=('normalized_url',), name='unique_endpoint_normalized_url'),
        ),
    ]
