# Generated by Django 6.0.6 on 2026-06-30 13:00

from django.conf import settings
from django.db import migrations, models


def _details_text(details, key, max_length):
    if not isinstance(details, dict):
        return ""
    value = details.get(key, "")
    if value is None or isinstance(value, (dict, list, tuple)):
        return ""
    return str(value)[:max_length]


def populate_audit_filter_columns(apps, schema_editor):
    AuditEvent = apps.get_model("core", "AuditEvent")
    batch = []
    for event in AuditEvent.objects.all().only("id", "details").iterator(chunk_size=1000):
        event.storage_id = _details_text(event.details, "storage_id", 120)
        event.path = _details_text(event.details, "path", 1024)
        event.target_preallocation = _details_text(event.details, "target_preallocation", 40)
        batch.append(event)
        if len(batch) >= 1000:
            AuditEvent.objects.bulk_update(batch, ["storage_id", "path", "target_preallocation"])
            batch = []
    if batch:
        AuditEvent.objects.bulk_update(batch, ["storage_id", "path", "target_preallocation"])


def clear_audit_filter_columns(apps, schema_editor):
    AuditEvent = apps.get_model("core", "AuditEvent")
    AuditEvent.objects.update(storage_id="", path="", target_preallocation="")


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_reconcile_migration_state'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='auditevent',
            name='path',
            field=models.CharField(blank=True, max_length=1024),
        ),
        migrations.AddField(
            model_name='auditevent',
            name='storage_id',
            field=models.CharField(blank=True, max_length=120),
        ),
        migrations.AddField(
            model_name='auditevent',
            name='target_preallocation',
            field=models.CharField(blank=True, max_length=40),
        ),
        migrations.RunPython(populate_audit_filter_columns, clear_audit_filter_columns),
        migrations.AddIndex(
            model_name='auditevent',
            index=models.Index(fields=['storage_id', 'timestamp'], name='core_audit_store_time_idx'),
        ),
        migrations.AddIndex(
            model_name='auditevent',
            index=models.Index(fields=['storage_id', 'path', 'target_preallocation'], name='core_audit_store_path_pre_idx'),
        ),
    ]
