# Generated by Codex on 2026-06-30

from django.db import migrations, models


def _metadata_text(metadata, key, max_length):
    if not isinstance(metadata, dict):
        return ""
    value = metadata.get(key, "")
    if value is None or isinstance(value, (dict, list, tuple)):
        return ""
    return str(value)[:max_length]


def populate_trash_storage_id(apps, schema_editor):
    TrashItem = apps.get_model("core", "TrashItem")
    batch = []
    for item in TrashItem.objects.all().only("id", "metadata").iterator(chunk_size=1000):
        item.storage_id = _metadata_text(item.metadata, "storage_id", 120)
        batch.append(item)
        if len(batch) >= 1000:
            TrashItem.objects.bulk_update(batch, ["storage_id"])
            batch = []
    if batch:
        TrashItem.objects.bulk_update(batch, ["storage_id"])


def clear_trash_storage_id(apps, schema_editor):
    TrashItem = apps.get_model("core", "TrashItem")
    TrashItem.objects.update(storage_id="")


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0007_audit_event_filter_columns"),
    ]

    operations = [
        migrations.AddField(
            model_name="trashitem",
            name="storage_id",
            field=models.CharField(blank=True, max_length=120),
        ),
        migrations.RunPython(populate_trash_storage_id, clear_trash_storage_id),
        migrations.AddIndex(
            model_name="trashitem",
            index=models.Index(fields=["storage_id", "restore_status", "moved_at"], name="core_trash_store_status_idx"),
        ),
    ]
