# Generated by Django 6.0.7 on 2026-07-17 16:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_backfill_endpoint_normalized_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='proxmoxcluster',
            name='ingestion_quarantined',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='proxmoxcluster',
            name='quarantine_reason',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='proxmoxcluster',
            name='quarantined_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.CreateModel(
            name='ClusterTransportTrust',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('mode', models.CharField(choices=[('public', 'Publicly trusted'), ('ca_pem', 'Internal CA bundle')], default='public', max_length=20)),
                ('ca_pem', models.TextField(blank=True)),
                ('approved_at', models.DateTimeField(blank=True, null=True)),
                ('details', models.JSONField(blank=True, default=dict)),
                ('cluster', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='transport_trust', to='core.proxmoxcluster')),
            ],
            options={
                'ordering': ['cluster__key'],
            },
        ),
    ]
