# Generated by Django 6.0.6 on 2026-07-01 20:26

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_trashitem_storage_id'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ScheduledAction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=160)),
                ('enabled', models.BooleanField(default=True)),
                ('action_type', models.CharField(choices=[('start', 'Start'), ('shutdown', 'Shutdown'), ('stop', 'Stop'), ('reboot', 'Reboot')], max_length=40)),
                ('action_timeout_seconds', models.PositiveIntegerField(default=1800)),
                ('target_type', models.CharField(choices=[('vm', 'VM'), ('ct', 'Container')], max_length=20)),
                ('target_vmid', models.PositiveIntegerField()),
                ('target_node', models.CharField(blank=True, max_length=120)),
                ('target_name_snapshot', models.CharField(blank=True, max_length=255)),
                ('parameters', models.JSONField(blank=True, default=dict)),
                ('schedule_type', models.CharField(choices=[('once', 'Once'), ('recurring', 'Recurring')], default='once', max_length=20)),
                ('run_at', models.DateTimeField(blank=True, null=True)),
                ('recurrence', models.JSONField(blank=True, default=dict)),
                ('recurrence_kind', models.CharField(choices=[('advanced', 'Advanced'), ('daily', 'Daily'), ('weekly', 'Weekly'), ('monthly_ordinal', 'Monthly ordinal'), ('monthly_day', 'Monthly day')], default='advanced', max_length=40)),
                ('timezone', models.CharField(default='UTC', max_length=80)),
                ('catch_up_policy', models.CharField(choices=[('skip_missed', 'Skip missed'), ('run_once_late', 'Run once late')], default='skip_missed', max_length=40)),
                ('max_lateness_minutes', models.PositiveIntegerField(default=0)),
                ('last_run_at', models.DateTimeField(blank=True, null=True)),
                ('next_run_at', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('last_status', models.CharField(choices=[('never_run', 'Never run'), ('queued', 'Queued'), ('completed', 'Completed'), ('failed', 'Failed'), ('skipped', 'Skipped'), ('missed', 'Missed'), ('timeout', 'Timed out')], default='never_run', max_length=40)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='pve_helper_scheduled_actions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-enabled', 'next_run_at', 'name'],
            },
        ),
        migrations.CreateModel(
            name='ScheduledActionRun',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('planned_for', models.DateTimeField()),
                ('occurrence_key', models.CharField(max_length=160)),
                ('started_at', models.DateTimeField(blank=True, null=True)),
                ('finished_at', models.DateTimeField(blank=True, null=True)),
                ('status', models.CharField(choices=[('queued', 'Queued'), ('preflight', 'Preflight'), ('submitted', 'Submitted'), ('polling', 'Polling'), ('completed', 'Completed'), ('failed', 'Failed'), ('skipped', 'Skipped'), ('missed', 'Missed'), ('timeout', 'Timed out'), ('stale', 'Stale')], default='queued', max_length=40)),
                ('outcome', models.CharField(blank=True, choices=[('success', 'Success'), ('success_noop', 'Success - no action needed'), ('failure', 'Failure'), ('skipped', 'Skipped'), ('missed', 'Missed'), ('timeout', 'Timed out'), ('stale', 'Stale')], max_length=60)),
                ('proxmox_task_upid', models.CharField(blank=True, max_length=512)),
                ('proxmox_task_node', models.CharField(blank=True, max_length=120)),
                ('preflight_snapshot', models.JSONField(blank=True, default=dict)),
                ('result', models.JSONField(blank=True, default=dict)),
                ('error', models.TextField(blank=True)),
                ('scheduled_action', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='runs', to='core.scheduledaction')),
                ('triggered_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='pve_helper_scheduled_action_runs', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-planned_for', '-created_at'],
            },
        ),
        migrations.AddIndex(
            model_name='scheduledaction',
            index=models.Index(fields=['enabled', 'next_run_at'], name='core_sched_enabled_next_idx'),
        ),
        migrations.AddIndex(
            model_name='scheduledaction',
            index=models.Index(fields=['target_type', 'target_vmid'], name='core_sched_target_idx'),
        ),
        migrations.AddIndex(
            model_name='scheduledaction',
            index=models.Index(fields=['action_type'], name='core_sched_action_idx'),
        ),
        migrations.AddIndex(
            model_name='scheduledaction',
            index=models.Index(fields=['created_by'], name='core_sched_created_by_idx'),
        ),
        migrations.AddIndex(
            model_name='scheduledactionrun',
            index=models.Index(fields=['scheduled_action', 'status'], name='core_schedrun_as_idx'),
        ),
        migrations.AddIndex(
            model_name='scheduledactionrun',
            index=models.Index(fields=['status', 'planned_for'], name='core_schedrun_status_plan_idx'),
        ),
        migrations.AddIndex(
            model_name='scheduledactionrun',
            index=models.Index(fields=['proxmox_task_upid'], name='core_schedrun_upid_idx'),
        ),
        migrations.AddConstraint(
            model_name='scheduledactionrun',
            constraint=models.UniqueConstraint(fields=('scheduled_action', 'occurrence_key'), name='uniq_schedaction_occurrence'),
        ),
    ]
