# Generated by Codex on 2026-07-02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0009_scheduledaction_scheduledactionrun_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="scheduledaction",
            name="name",
            field=models.CharField(max_length=160, unique=True),
        ),
    ]
