# Generated by Django 6.0.7 on 2026-07-17 18:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_cluster_transport_trust'),
    ]

    operations = [
        migrations.AddField(
            model_name='consolesession',
            name='cluster',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='console_sessions', to='core.proxmoxcluster'),
        ),
    ]
