# Generated by Django 6.0.7 on 2026-08-10 18:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_scheduled_action_settings'),
    ]

    operations = [
        migrations.CreateModel(
            name='ClusterMembershipState',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('topology_role', models.CharField(default='unknown', max_length=32)),
                ('transition_pending', models.BooleanField(default=False)),
                ('pending_topology_role', models.CharField(blank=True, default='', max_length=32)),
                ('member_count', models.PositiveIntegerField(default=0)),
                ('quorate', models.BooleanField(default=False)),
                ('observed_from', models.CharField(blank=True, default='', max_length=120)),
                ('cluster', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='membership_state', to='core.proxmoxcluster')),
            ],
            options={
                'verbose_name': 'cluster membership state',
                'verbose_name_plural': 'cluster membership states',
            },
        ),
        migrations.CreateModel(
            name='ClusterNodeState',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('node', models.CharField(max_length=120)),
                ('nodeid', models.IntegerField(blank=True, null=True)),
                ('present', models.BooleanField(default=True)),
                ('online', models.BooleanField(default=False)),
                ('reported_ring_address', models.CharField(blank=True, default='', max_length=255)),
                ('membership_generation', models.BigIntegerField(default=0)),
                ('first_seen_at', models.DateTimeField(blank=True, null=True)),
                ('last_seen_at', models.DateTimeField(blank=True, null=True)),
                ('cluster', models.ForeignKey(db_index=False, on_delete=django.db.models.deletion.CASCADE, related_name='node_states', to='core.proxmoxcluster')),
            ],
            options={
                'verbose_name': 'cluster node state',
                'verbose_name_plural': 'cluster node states',
                'indexes': [models.Index(fields=['cluster', 'present'], name='core_node_state_present_idx')],
                'constraints': [models.UniqueConstraint(fields=('cluster', 'node'), name='core_cluster_node_state_uniq')],
            },
        ),
        migrations.CreateModel(
            name='ClusterProjectionCoverage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('domain', models.CharField(max_length=64)),
                ('node', models.CharField(blank=True, max_length=120, null=True)),
                ('generation', models.BigIntegerField(default=0)),
                ('based_on_generation', models.BigIntegerField(blank=True, null=True)),
                ('complete', models.BooleanField(default=False)),
                ('attempted_at', models.DateTimeField(blank=True, null=True)),
                ('observed_at', models.DateTimeField(blank=True, null=True)),
                ('error_code', models.CharField(blank=True, default='', max_length=64)),
                ('cluster', models.ForeignKey(db_index=False, on_delete=django.db.models.deletion.CASCADE, related_name='projection_coverage', to='core.proxmoxcluster')),
            ],
            options={
                'verbose_name': 'cluster projection coverage',
                'verbose_name_plural': 'cluster projection coverage',
                'constraints': [models.UniqueConstraint(fields=('cluster', 'domain', 'node'), name='core_projection_coverage_uniq', nulls_distinct=False)],
            },
        ),
    ]
