# Generated by Django 6.0.7 on 2026-08-11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0010_clustermembershipstate_clusternodestate_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="clustermembershipstate",
            name="pending_topology_role",
        ),
        migrations.RemoveField(
            model_name="clustermembershipstate",
            name="transition_pending",
        ),
        migrations.AddField(
            model_name="clustermembershipstate",
            name="membership_generation",
            field=models.PositiveBigIntegerField(default=0),
        ),
        migrations.RemoveConstraint(
            model_name="clusternodestate",
            name="core_cluster_node_state_uniq",
        ),
        migrations.RenameField(
            model_name="clusternodestate",
            old_name="node",
            new_name="node_name",
        ),
        migrations.RenameField(
            model_name="clusternodestate",
            old_name="first_seen_at",
            new_name="first_discovered_at",
        ),
        migrations.RenameField(
            model_name="clusternodestate",
            old_name="last_seen_at",
            new_name="last_discovered_at",
        ),
        migrations.AlterField(
            model_name="clusternodestate",
            name="nodeid",
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="clusternodestate",
            name="membership_generation",
            field=models.PositiveBigIntegerField(default=0),
        ),
        migrations.AddField(
            model_name="clusternodestate",
            name="runtime_generation",
            field=models.PositiveBigIntegerField(default=0),
        ),
        migrations.AddField(
            model_name="clusternodestate",
            name="cpu_usage",
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="clusternodestate",
            name="cpu_wait",
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="clusternodestate",
            name="cpu_model",
            field=models.CharField(blank=True, default="", max_length=255),
        ),
        migrations.AddField(
            model_name="clusternodestate",
            name="cpu_sockets",
            field=models.PositiveSmallIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="clusternodestate",
            name="cpu_cores",
            field=models.PositiveSmallIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="clusternodestate",
            name="memory_total_bytes",
            field=models.PositiveBigIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="clusternodestate",
            name="memory_used_bytes",
            field=models.PositiveBigIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="clusternodestate",
            name="swap_total_bytes",
            field=models.PositiveBigIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="clusternodestate",
            name="swap_used_bytes",
            field=models.PositiveBigIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="clusternodestate",
            name="rootfs_total_bytes",
            field=models.PositiveBigIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="clusternodestate",
            name="rootfs_used_bytes",
            field=models.PositiveBigIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="clusternodestate",
            name="load_average_1m",
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="clusternodestate",
            name="load_average_5m",
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="clusternodestate",
            name="load_average_15m",
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="clusternodestate",
            name="uptime_seconds",
            field=models.PositiveBigIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="clusternodestate",
            name="pve_version",
            field=models.CharField(blank=True, default="", max_length=120),
        ),
        migrations.AddField(
            model_name="clusternodestate",
            name="kernel_version",
            field=models.CharField(blank=True, default="", max_length=255),
        ),
        migrations.AddField(
            model_name="clusternodestate",
            name="current_kernel_release",
            field=models.CharField(blank=True, default="", max_length=255),
        ),
        migrations.AddField(
            model_name="clusternodestate",
            name="boot_mode",
            field=models.CharField(blank=True, default="", max_length=32),
        ),
        migrations.AddField(
            model_name="clusternodestate",
            name="secure_boot_enabled",
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AddConstraint(
            model_name="clusternodestate",
            constraint=models.UniqueConstraint(
                fields=("cluster", "node_name"),
                name="core_cluster_node_state_uniq",
            ),
        ),
        migrations.AddConstraint(
            model_name="clusternodestate",
            constraint=models.CheckConstraint(
                condition=~models.Q(node_name="") & ~models.Q(node_name__contains=":"),
                name="core_cluster_node_state_valid_ref",
            ),
        ),
        migrations.RemoveConstraint(
            model_name="clusterprojectioncoverage",
            name="core_projection_coverage_uniq",
        ),
        migrations.RenameField(
            model_name="clusterprojectioncoverage",
            old_name="node",
            new_name="node_name",
        ),
        migrations.AlterField(
            model_name="clusterprojectioncoverage",
            name="domain",
            field=models.CharField(
                choices=[("membership", "Membership"), ("node_runtime", "Node runtime")],
                max_length=64,
            ),
        ),
        migrations.AlterField(
            model_name="clusterprojectioncoverage",
            name="generation",
            field=models.PositiveBigIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name="clusterprojectioncoverage",
            name="based_on_generation",
            field=models.PositiveBigIntegerField(blank=True, null=True),
        ),
        migrations.AddConstraint(
            model_name="clusterprojectioncoverage",
            constraint=models.UniqueConstraint(
                fields=("cluster", "domain", "node_name"),
                name="core_projection_coverage_uniq",
                nulls_distinct=False,
            ),
        ),
        migrations.AddConstraint(
            model_name="clusterprojectioncoverage",
            constraint=models.CheckConstraint(
                condition=(
                    models.Q(
                        domain="membership",
                        node_name__isnull=True,
                        based_on_generation__isnull=True,
                    )
                    | (
                        models.Q(
                            domain="node_runtime",
                            node_name__isnull=False,
                            based_on_generation__isnull=False,
                        )
                        & ~models.Q(node_name="")
                        & ~models.Q(node_name__contains=":")
                    )
                ),
                name="core_projection_coverage_scope",
            ),
        ),
    ]
