# Generated by Django 6.0.7 on 2026-07-17 18:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_console_session_cluster'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='currentguestinventory',
            name='unique_current_guest_identity',
        ),
        migrations.RemoveIndex(
            model_name='currentguestinventory',
            name='core_curguest_type_vmid_idx',
        ),
        migrations.AddField(
            model_name='currentguestinventory',
            name='cluster',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='current_guests', to='core.proxmoxcluster'),
        ),
        migrations.AddField(
            model_name='currentguestinventorystate',
            name='cluster',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='inventory_state', to='core.proxmoxcluster'),
        ),
        migrations.AddField(
            model_name='currentguestinventorystate',
            name='unreachable',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='proxmoxinventory',
            name='cluster',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='proxmox_objects', to='core.proxmoxcluster'),
        ),
        migrations.AddIndex(
            model_name='currentguestinventory',
            index=models.Index(fields=['cluster', 'node', 'object_type', 'vmid'], name='core_curg_cluster_node_idx'),
        ),
        migrations.AddIndex(
            model_name='proxmoxinventory',
            index=models.Index(fields=['cluster', 'object_type', 'vmid'], name='core_pinv_cluster_type_vmid'),
        ),
        migrations.AddConstraint(
            model_name='currentguestinventory',
            constraint=models.UniqueConstraint(fields=('cluster', 'object_type', 'vmid'), name='unique_current_guest_cluster_identity', nulls_distinct=False),
        ),
        migrations.AddConstraint(
            model_name='currentguestinventorystate',
            constraint=models.UniqueConstraint(fields=('cluster',), name='unique_inventory_state_per_cluster', nulls_distinct=False),
        ),
    ]
