# Generated by Django 6.0.7 on 2026-08-11

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


IDENTITY_TRIGGER_SQL = """
    CREATE FUNCTION core_enrollment_enforce_identity() RETURNS trigger
    LANGUAGE plpgsql AS $$
    DECLARE
        cluster_key text;
        expected_snapshot text;
    BEGIN
        SELECT "key" INTO STRICT cluster_key
        FROM core_proxmoxcluster
        WHERE id = NEW.cluster_id;

        expected_snapshot := 'nr1:' || cluster_key || ':' || NEW.node_name;
        IF NEW.node_ref_snapshot IS DISTINCT FROM expected_snapshot THEN
            RAISE EXCEPTION 'Enrollment NodeRef snapshot does not match its cluster and node.'
                USING ERRCODE = '23514',
                      CONSTRAINT = 'core_cluster_node_enrollment_snapshot_matches';
        END IF;

        IF TG_OP = 'UPDATE' AND (
            NEW.cluster_id IS DISTINCT FROM OLD.cluster_id
            OR NEW.node_name IS DISTINCT FROM OLD.node_name
            OR NEW.node_ref_snapshot IS DISTINCT FROM OLD.node_ref_snapshot
        ) THEN
            RAISE EXCEPTION 'Enrollment NodeRef identity is immutable.'
                USING ERRCODE = '23514',
                      CONSTRAINT = 'core_cluster_node_enrollment_identity_immutable';
        END IF;

        RETURN NEW;
    END;
    $$;

    CREATE TRIGGER core_enrollment_enforce_identity_trigger
    BEFORE INSERT OR UPDATE ON core_clusternodeenrollment
    FOR EACH ROW EXECUTE FUNCTION core_enrollment_enforce_identity();
"""

IDENTITY_TRIGGER_REVERSE_SQL = """
    DROP TRIGGER IF EXISTS core_enrollment_enforce_identity_trigger
        ON core_clusternodeenrollment;
    DROP FUNCTION IF EXISTS core_enrollment_enforce_identity();
"""


def create_identity_trigger(_apps, schema_editor):
    # The ordinary suite and deployments use PostgreSQL, where this trigger is the
    # database-level identity guarantee. Playwright deliberately migrates a
    # throwaway SQLite database; PostgreSQL's PL/pgSQL syntax is neither supported
    # nor needed for that isolated render fixture.
    if schema_editor.connection.vendor == "postgresql":
        schema_editor.execute(IDENTITY_TRIGGER_SQL)


def drop_identity_trigger(_apps, schema_editor):
    if schema_editor.connection.vendor == "postgresql":
        schema_editor.execute(IDENTITY_TRIGGER_REVERSE_SQL)


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0011_correct_cluster_projection_contract"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="proxmoxcluster",
            name="enrollment_contract_version",
            field=models.PositiveSmallIntegerField(default=0),
        ),
        migrations.AddField(
            model_name="proxmoxcluster",
            name="enrollment_generation",
            field=models.PositiveBigIntegerField(default=0),
        ),
        migrations.AddField(
            model_name="proxmoxcluster",
            name="enrollment_activated_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="proxmoxcluster",
            name="enrollment_activated_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="+",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.CreateModel(
            name="ClusterNodeEnrollment",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("node_name", models.CharField(max_length=120)),
                ("node_ref_snapshot", models.CharField(editable=False, max_length=188)),
                (
                    "mode",
                    models.CharField(
                        choices=[("managed", "Managed"), ("safety_only", "Safety only")],
                        max_length=16,
                    ),
                ),
                ("enrolled_at", models.DateTimeField()),
                ("mode_changed_at", models.DateTimeField(blank=True, null=True)),
                ("mode_change_reason", models.CharField(blank=True, default="", max_length=1000)),
                (
                    "cluster",
                    models.ForeignKey(
                        db_index=False,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="node_enrollments",
                        to="core.proxmoxcluster",
                    ),
                ),
                (
                    "enrolled_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "mode_changed_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "onboarded_via_endpoint",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to="core.proxmoxendpoint",
                    ),
                ),
            ],
            options={
                "verbose_name": "cluster node enrollment",
                "verbose_name_plural": "cluster node enrollments",
                "constraints": [
                    models.UniqueConstraint(
                        fields=("cluster", "node_name"),
                        name="core_cluster_node_enrollment_uniq",
                    ),
                    models.CheckConstraint(
                        condition=~models.Q(node_name="") & ~models.Q(node_name__contains=":"),
                        name="core_cluster_node_enrollment_valid_ref",
                    ),
                    models.CheckConstraint(
                        condition=models.Q(mode__in=("managed", "safety_only")),
                        name="core_cluster_node_enrollment_valid_mode",
                    ),
                    models.CheckConstraint(
                        condition=~models.Q(node_ref_snapshot=""),
                        name="core_cluster_node_enrollment_snapshot_nonempty",
                    ),
                ],
            },
        ),
        migrations.RunPython(create_identity_trigger, drop_identity_trigger),
    ]
