# Generated by Django 6.0.7 on 2026-08-12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0012_cluster_node_enrollment"),
    ]

    operations = [
        migrations.AddField(
            model_name="clustermembershipstate",
            name="pending_topology_role",
            field=models.CharField(default="unknown", max_length=32),
        ),
        migrations.AddField(
            model_name="clustermembershipstate",
            name="transition_pending",
            field=models.BooleanField(default=False),
        ),
        migrations.AddConstraint(
            model_name="clustermembershipstate",
            constraint=models.CheckConstraint(
                condition=(
                    models.Q(pending_topology_role="unknown", transition_pending=False)
                    | (
                        models.Q(transition_pending=True)
                        & ~models.Q(pending_topology_role__in=("", "unknown"))
                        & ~models.Q(pending_topology_role=models.F("topology_role"))
                    )
                ),
                name="core_membership_pending_role_coherent",
            ),
        ),
        migrations.CreateModel(
            name="ClusterTopologyHandoffStorageBinding",
            fields=[
                (
                    "id",
                    models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID"),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("source_cluster_key_snapshot", models.CharField(max_length=63)),
                ("storage_id", models.CharField(max_length=120)),
                (
                    "scope",
                    models.CharField(choices=[("shared", "Shared"), ("node", "Node")], max_length=12),
                ),
                ("node", models.CharField(blank=True, max_length=120, null=True)),
                (
                    "status",
                    models.CharField(
                        choices=[("pending", "Pending"), ("applied", "Applied"), ("refused", "Refused")],
                        default="pending",
                        max_length=12,
                    ),
                ),
                ("applied_at", models.DateTimeField(blank=True, null=True)),
                ("refusal_reason", models.CharField(blank=True, default="", max_length=255)),
                (
                    "cluster",
                    models.ForeignKey(
                        db_index=False,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="topology_handoff_storage_bindings",
                        to="core.proxmoxcluster",
                    ),
                ),
                (
                    "mount",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="topology_handoff_intents",
                        to="core.storagemount",
                    ),
                ),
            ],
            options={
                "ordering": ["cluster__key", "storage_id", "node"],
                "constraints": [
                    models.UniqueConstraint(
                        fields=("cluster", "storage_id", "node"),
                        name="core_topology_handoff_binding_uniq",
                        nulls_distinct=False,
                    ),
                    models.CheckConstraint(
                        condition=(
                            models.Q(node__isnull=True, scope="shared")
                            | (models.Q(node__isnull=False, scope="node") & ~models.Q(node=""))
                        ),
                        name="core_topology_handoff_binding_scope",
                    ),
                    models.CheckConstraint(
                        condition=models.Q(status__in=("pending", "applied", "refused")),
                        name="core_topology_handoff_binding_status",
                    ),
                    models.CheckConstraint(
                        condition=~models.Q(source_cluster_key_snapshot=""),
                        name="core_topology_handoff_source_nonempty",
                    ),
                ],
            },
        ),
    ]
