# Generated by Codex on 2026-07-08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0013_consolesession"),
    ]

    operations = [
        migrations.AlterField(
            model_name="scheduledaction",
            name="last_status",
            field=models.CharField(
                choices=[
                    ("never_run", "Never run"),
                    ("queued", "Queued"),
                    ("completed", "Completed"),
                    ("failed", "Failed"),
                    ("skipped", "Skipped"),
                    ("missed", "Missed"),
                    ("timeout", "Timed out"),
                    ("cancelled", "Cancelled"),
                ],
                default="never_run",
                max_length=40,
            ),
        ),
        migrations.AlterField(
            model_name="scheduledactionrun",
            name="outcome",
            field=models.CharField(
                blank=True,
                choices=[
                    ("success", "Success"),
                    ("success_noop", "Success - no action needed"),
                    ("failure", "Failure"),
                    ("skipped", "Skipped"),
                    ("missed", "Missed"),
                    ("timeout", "Timed out"),
                    ("stale", "Stale"),
                    ("cancelled", "Cancelled"),
                ],
                max_length=60,
            ),
        ),
        migrations.AlterField(
            model_name="scheduledactionrun",
            name="status",
            field=models.CharField(
                choices=[
                    ("queued", "Queued"),
                    ("preflight", "Preflight"),
                    ("submitted", "Submitted"),
                    ("polling", "Polling"),
                    ("completed", "Completed"),
                    ("failed", "Failed"),
                    ("skipped", "Skipped"),
                    ("missed", "Missed"),
                    ("timeout", "Timed out"),
                    ("stale", "Stale"),
                    ("cancelled", "Cancelled"),
                ],
                default="queued",
                max_length=40,
            ),
        ),
    ]
