# Generated by Django 6.0.7 on 2026-07-18 05:00

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


def backfill_durable_cluster_identity(apps, schema_editor):
    AuditEvent = apps.get_model("core", "AuditEvent")
    CurrentGuestInventory = apps.get_model("core", "CurrentGuestInventory")
    ProxmoxCluster = apps.get_model("core", "ProxmoxCluster")
    ProxmoxEndpoint = apps.get_model("core", "ProxmoxEndpoint")
    ScheduledAction = apps.get_model("core", "ScheduledAction")

    clusters = {cluster.key: cluster for cluster in ProxmoxCluster.objects.all()}
    enabled = [cluster for cluster in clusters.values() if cluster.enabled]
    sole_enabled = enabled[0] if len(enabled) == 1 else None

    for action in ScheduledAction.objects.filter(cluster__isnull=True).iterator():
        candidates = CurrentGuestInventory.objects.filter(
            object_type=action.target_type,
            vmid=action.target_vmid,
            cluster__isnull=False,
        )
        if action.target_node:
            node_candidates = candidates.filter(node=action.target_node)
            if node_candidates.values("cluster_id").distinct().count() == 1:
                candidates = node_candidates
        cluster_ids = list(candidates.values_list("cluster_id", flat=True).distinct()[:2])
        cluster_id = cluster_ids[0] if len(cluster_ids) == 1 else None
        if cluster_id is None and sole_enabled is not None:
            cluster_id = sole_enabled.pk
        if cluster_id is not None:
            ScheduledAction.objects.filter(pk=action.pk).update(cluster_id=cluster_id)

    cluster_specific_object_types = {
        "guest",
        "scheduled_action",
        "scheduled_action_run",
        "tag",
        "tag_inventory",
    }
    for event in AuditEvent.objects.filter(cluster__isnull=True).iterator():
        details = event.details if isinstance(event.details, dict) else {}
        cluster = clusters.get(str(details.get("cluster_key") or ""))
        if cluster is None:
            endpoint_url = str(details.get("proxmox_endpoint") or "")
            endpoint = (
                ProxmoxEndpoint.objects.filter(url=endpoint_url, cluster__isnull=False).first()
                if endpoint_url
                else None
            )
            cluster = endpoint.cluster if endpoint is not None else None
        if (
            cluster is None
            and sole_enabled is not None
            and (event.object_type in cluster_specific_object_types or event.module == "vms")
        ):
            cluster = sole_enabled
        if cluster is not None:
            AuditEvent.objects.filter(pk=event.pk).update(
                cluster_id=cluster.pk,
                cluster_key_snapshot=cluster.key,
            )


def noop_reverse(apps, schema_editor):
    # Identity evidence is intentionally retained on rollback; old code ignores it.
    pass


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0013_cluster_cache_generation'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='auditevent',
            name='cluster',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='audit_events', to='core.proxmoxcluster'),
        ),
        migrations.AddField(
            model_name='auditevent',
            name='cluster_key_snapshot',
            field=models.CharField(blank=True, max_length=63),
        ),
        migrations.AddField(
            model_name='scheduledaction',
            name='cluster',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='scheduled_actions', to='core.proxmoxcluster'),
        ),
        migrations.AlterField(
            model_name='proxmoxendpoint',
            name='name',
            field=models.CharField(max_length=120),
        ),
        migrations.RunPython(backfill_durable_cluster_identity, noop_reverse),
        migrations.AddIndex(
            model_name='auditevent',
            index=models.Index(fields=['cluster_key_snapshot', 'timestamp'], name='core_audit_cluster_time_idx'),
        ),
        migrations.AddIndex(
            model_name='consolesession',
            index=models.Index(fields=['cluster', 'target_type', 'target_vmid'], name='core_con_cluster_target_idx'),
        ),
        migrations.AddIndex(
            model_name='consolesession',
            index=models.Index(fields=['cluster', 'target_node', 'target_type', 'target_vmid'], name='core_con_cluster_node_idx'),
        ),
        migrations.AddIndex(
            model_name='scheduledaction',
            index=models.Index(fields=['cluster', 'target_type', 'target_vmid'], name='core_sched_cluster_target_idx'),
        ),
        migrations.AddIndex(
            model_name='scheduledaction',
            index=models.Index(fields=['cluster', 'target_node', 'target_type', 'target_vmid'], name='core_sched_cluster_node_idx'),
        ),
        migrations.AddConstraint(
            model_name='proxmoxendpoint',
            constraint=models.UniqueConstraint(fields=('cluster', 'name'), name='unique_endpoint_name_per_cluster', nulls_distinct=False),
        ),
    ]
