# Generated by Codex on 2026-07-12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0014_cancelled_task_statuses"),
    ]

    operations = [
        migrations.AddField(
            model_name="scheduledaction",
            name="deleted_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="scheduledaction",
            name="name",
            field=models.CharField(max_length=160),
        ),
        migrations.AddConstraint(
            model_name="scheduledaction",
            constraint=models.UniqueConstraint(
                condition=models.Q(deleted_at__isnull=True),
                fields=("name",),
                name="uniq_active_scheduled_action_name",
            ),
        ),
        migrations.AlterField(
            model_name="scheduledactionrun",
            name="scheduled_action",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="runs",
                to="core.scheduledaction",
            ),
        ),
    ]
