# Generated by Codex on 2026-07-12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0015_scheduledaction_soft_delete"),
    ]

    operations = [
        migrations.AlterField(
            model_name="fileinventory",
            name="classification",
            field=models.CharField(
                choices=[
                    ("referenced", "Referenced"),
                    ("likely_orphan", "Likely orphan"),
                    ("unknown", "Unknown"),
                    ("classification_blocked", "Classification blocked"),
                    ("trash", "Trash"),
                    ("infrastructure", "Infrastructure"),
                    ("proxmox_content", "Proxmox content"),
                    ("import_source", "Import source"),
                ],
                default="unknown",
                max_length=40,
            ),
        ),
    ]
