# Generated by Django 6.0.7 on 2026-07-18 13:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0016_close_read_model_cluster_rollout'),
    ]

    operations = [
        migrations.AddField(
            model_name='currentguestinventorystate',
            name='linked_clone_lineage',
            field=models.JSONField(blank=True, default=dict),
        ),
    ]
