# Generated by Django 6.0.7 on 2026-07-19 09:42

import uuid

import django.db.models.deletion
from django.db import migrations, models


def _truthy(value):
    return str(value or "").lower() in {"1", "true", "yes", "on"}


def _list_value(value):
    if isinstance(value, list):
        return [str(item) for item in value if str(item)]
    return [item.strip() for item in str(value or "").split(",") if item.strip()]


def _integer(value):
    try:
        return int(value)
    except (TypeError, ValueError):
        return None


def _beneath_storage_root(value):
    value = str(value or "").rstrip("/")
    prefix = "/storages/"
    if not value.startswith(prefix):
        return ""
    relative = value[len(prefix) :].strip("/")
    if not relative or any(part in {"", ".", ".."} for part in relative.split("/")):
        return ""
    return relative


def backfill_storage_foundation(apps, schema_editor):
    StorageMount = apps.get_model("core", "StorageMount")
    ScanRun = apps.get_model("core", "ScanRun")
    ProxmoxInventory = apps.get_model("core", "ProxmoxInventory")
    ProxmoxStorageConsumer = apps.get_model("core", "ProxmoxStorageConsumer")
    ClusterStorage = apps.get_model("core", "ClusterStorage")
    ClusterStorageNodeState = apps.get_model("core", "ClusterStorageNodeState")
    ClusterStorageMount = apps.get_model("core", "ClusterStorageMount")
    StorageCatalogState = apps.get_model("core", "StorageCatalogState")
    TrashItem = apps.get_model("core", "TrashItem")

    for mount in StorageMount.objects.all().iterator():
        mount.mount_key = uuid.uuid4()
        mount.relative_path = _beneath_storage_root(mount.path)
        mount.trash_relative_path = _beneath_storage_root(mount.trash_path)
        backend = str(mount.export or "").strip()
        server, separator, suffix = backend.partition(":")
        mount.backend_identity = (
            f"{server.lower()}:{suffix}" if separator and server else backend
        )
        if mount.export and ":" in mount.export:
            mount.filesystem_type = "nfs"
        mount.save(
            update_fields=[
                "mount_key",
                "relative_path",
                "trash_relative_path",
                "backend_identity",
                "filesystem_type",
            ]
        )

    mounts_by_legacy_id = {
        mount.storage_id: mount
        for mount in StorageMount.objects.all().iterator()
    }
    for item in TrashItem.objects.filter(mount__isnull=True).iterator():
        storage_id = item.storage_id or dict(item.metadata or {}).get("storage_id", "")
        mount = mounts_by_legacy_id.get(str(storage_id))
        if mount is None:
            raise RuntimeError(
                f"Trash item {item.pk} cannot be attributed to a unique storage mount."
            )
        item.mount_id = mount.pk
        item.save(update_fields=["mount"])

    latest_scan_ids = []
    seen_clusters = set()
    scans = (
        ScanRun.objects.filter(status="completed", proxmox_objects__cluster__isnull=False)
        .order_by("-finished_at", "-id")
        .distinct()
    )
    for scan in scans.iterator():
        cluster_ids = list(
            ProxmoxInventory.objects.filter(scan_run=scan, cluster__isnull=False)
            .values_list("cluster_id", flat=True)
            .distinct()
        )
        for cluster_id in cluster_ids:
            if cluster_id not in seen_clusters:
                latest_scan_ids.append((cluster_id, scan.id))
                seen_clusters.add(cluster_id)

    for cluster_id, scan_id in latest_scan_ids:
        latest_seen = None
        for item in ProxmoxInventory.objects.filter(
            scan_run_id=scan_id,
            cluster_id=cluster_id,
            object_type="storage",
        ).iterator():
            config = dict(item.config or {})
            node_status = config.get("node_status") if isinstance(config.get("node_status"), dict) else {}
            storage_id = str(config.get("storage") or item.name or node_status.get("storage") or "")
            if not storage_id:
                continue
            definition, _ = ClusterStorage.objects.update_or_create(
                cluster_id=cluster_id,
                storage_id=storage_id,
                defaults={
                    "storage_type": str(config.get("type") or node_status.get("type") or "unknown"),
                    "content": _list_value(config.get("content") or node_status.get("content")),
                    "shared": _truthy(config.get("shared") or node_status.get("shared")),
                    "nodes": _list_value(config.get("nodes")),
                    "disabled": _truthy(config.get("disable")),
                    "config": config,
                    "present": True,
                    "last_seen_at": item.created_at,
                },
            )
            ClusterStorageNodeState.objects.update_or_create(
                cluster_storage=definition,
                node=item.node,
                defaults={
                    "active": _truthy(node_status.get("active", item.status)),
                    "enabled": not _truthy(config.get("disable")),
                    "total_bytes": _integer(node_status.get("total")),
                    "used_bytes": _integer(node_status.get("used")),
                    "available_bytes": _integer(node_status.get("avail")),
                    "present": True,
                    "last_seen_at": item.created_at,
                },
            )
            if latest_seen is None or item.created_at > latest_seen:
                latest_seen = item.created_at
        StorageCatalogState.objects.update_or_create(
            cluster_id=cluster_id,
            defaults={
                "metadata_refreshed_at": latest_seen,
                "metadata_complete": False,
                "metadata_errors": {"backfill": "Stale scan seed; live reconciliation required."},
            },
        )

    for consumer in ProxmoxStorageConsumer.objects.select_related("storage").filter(
        cluster__isnull=False
    ).iterator():
        definition = ClusterStorage.objects.filter(
            cluster_id=consumer.cluster_id,
            storage_id=consumer.storage.storage_id,
        ).first()
        if definition is None:
            raise RuntimeError(
                "Storage consumer cannot be attributed to a cluster storage "
                f"definition: consumer={consumer.pk}."
            )
        if definition.shared:
            binding, _ = ClusterStorageMount.objects.get_or_create(
                cluster_storage=definition,
                node=None,
                defaults={"mount_id": consumer.storage_id, "scope": "shared"},
            )
        else:
            binding, _ = ClusterStorageMount.objects.get_or_create(
                cluster_storage=definition,
                node=consumer.expected_node_name,
                defaults={"mount_id": consumer.storage_id, "scope": "node"},
            )
        if binding.mount_id != consumer.storage_id:
            raise RuntimeError(
                "Storage consumers map one cluster storage scope to multiple mounts: "
                f"consumer={consumer.pk}."
            )


def reverse_storage_foundation_backfill(apps, schema_editor):
    # New projection/binding tables are removed by the reverse schema operations.
    # Legacy StorageMount fields are intentionally left populated until then.
    return None


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0017_currentguestinventorystate_linked_clone_lineage'),
    ]

    operations = [
        migrations.AddField(
            model_name='storagemount',
            name='backend_identity',
            field=models.CharField(blank=True, max_length=512),
        ),
        migrations.AddField(
            model_name='trashitem',
            name='mount',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='trash_items', to='core.storagemount'),
        ),
        migrations.AddField(
            model_name='storagemount',
            name='filesystem_type',
            field=models.CharField(blank=True, max_length=40),
        ),
        migrations.AddField(
            model_name='storagemount',
            name='mount_key',
            field=models.UUIDField(blank=True, editable=False, null=True),
        ),
        migrations.AddField(
            model_name='storagemount',
            name='relative_path',
            field=models.CharField(blank=True, max_length=512),
        ),
        migrations.AddField(
            model_name='storagemount',
            name='trash_relative_path',
            field=models.CharField(blank=True, max_length=512),
        ),
        migrations.CreateModel(
            name='ClusterStorage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('storage_id', models.CharField(max_length=120)),
                ('storage_type', models.CharField(max_length=40)),
                ('content', models.JSONField(blank=True, default=list)),
                ('shared', models.BooleanField(default=False)),
                ('nodes', models.JSONField(blank=True, default=list)),
                ('disabled', models.BooleanField(default=False)),
                ('config', models.JSONField(blank=True, default=dict)),
                ('present', models.BooleanField(default=True)),
                ('retired_at', models.DateTimeField(blank=True, null=True)),
                ('observed_metadata_generation', models.UUIDField(blank=True, null=True)),
                ('last_seen_at', models.DateTimeField(blank=True, null=True)),
                ('cluster', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='storage_definitions', to='core.proxmoxcluster')),
            ],
            options={
                'ordering': ['cluster__key', 'storage_id'],
            },
        ),
        migrations.CreateModel(
            name='ClusterStorageMount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('scope', models.CharField(choices=[('shared', 'Shared'), ('node', 'Node')], max_length=12)),
                ('node', models.CharField(blank=True, max_length=120, null=True)),
                ('cluster_storage', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mount_bindings', to='core.clusterstorage')),
                ('mount', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='cluster_bindings', to='core.storagemount')),
            ],
            options={
                'ordering': ['cluster_storage__cluster__key', 'cluster_storage__storage_id', 'node'],
            },
        ),
        migrations.CreateModel(
            name='ClusterStorageNodeState',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('node', models.CharField(max_length=120)),
                ('active', models.BooleanField(default=False)),
                ('enabled', models.BooleanField(default=True)),
                ('total_bytes', models.BigIntegerField(blank=True, null=True)),
                ('used_bytes', models.BigIntegerField(blank=True, null=True)),
                ('available_bytes', models.BigIntegerField(blank=True, null=True)),
                ('present', models.BooleanField(default=True)),
                ('observed_metadata_generation', models.UUIDField(blank=True, null=True)),
                ('last_seen_at', models.DateTimeField(blank=True, null=True)),
                ('cluster_storage', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='node_states', to='core.clusterstorage')),
            ],
            options={
                'ordering': ['cluster_storage__storage_id', 'node'],
            },
        ),
        migrations.CreateModel(
            name='ClusterStorageVolumeObservation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('node', models.CharField(max_length=120)),
                ('volid', models.CharField(max_length=512)),
                ('vmid', models.PositiveIntegerField(blank=True, null=True)),
                ('content', models.CharField(blank=True, max_length=40)),
                ('volume_format', models.CharField(blank=True, max_length=40)),
                ('size_bytes', models.BigIntegerField(blank=True, null=True)),
                ('used_bytes', models.BigIntegerField(blank=True, null=True)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('observed_volume_generation', models.UUIDField()),
                ('based_on_metadata_generation', models.UUIDField()),
                ('last_seen_at', models.DateTimeField()),
                ('cluster_storage', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='volume_observations', to='core.clusterstorage')),
            ],
            options={
                'ordering': ['cluster_storage__storage_id', 'node', 'volid'],
            },
        ),
        migrations.CreateModel(
            name='StorageCatalogState',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('metadata_generation', models.UUIDField(blank=True, null=True)),
                ('metadata_refreshed_at', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('metadata_last_attempt_at', models.DateTimeField(blank=True, null=True)),
                ('metadata_complete', models.BooleanField(default=False)),
                ('metadata_errors', models.JSONField(blank=True, default=dict)),
                ('volume_generation', models.UUIDField(blank=True, null=True)),
                ('volume_based_on_metadata_generation', models.UUIDField(blank=True, null=True)),
                ('volume_refreshed_at', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('volume_last_attempt_at', models.DateTimeField(blank=True, null=True)),
                ('volume_complete', models.BooleanField(default=False)),
                ('volume_errors', models.JSONField(blank=True, default=dict)),
                ('cluster', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='storage_catalog_state', to='core.proxmoxcluster')),
            ],
            options={
                'ordering': ['cluster__key'],
            },
        ),
        migrations.AddIndex(
            model_name='clusterstorage',
            index=models.Index(fields=['cluster', 'present', 'disabled'], name='core_cstorage_state_idx'),
        ),
        migrations.AddIndex(
            model_name='clusterstorage',
            index=models.Index(fields=['cluster', 'retired_at'], name='core_cstorage_retired_idx'),
        ),
        migrations.AddConstraint(
            model_name='clusterstorage',
            constraint=models.UniqueConstraint(fields=('cluster', 'storage_id'), name='unique_cluster_storage_definition'),
        ),
        migrations.AddConstraint(
            model_name='clusterstoragemount',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('node__isnull', True), ('scope', 'shared')), models.Q(('node__isnull', False), ('scope', 'node')), _connector='OR'), name='storage_mount_scope_matches_node'),
        ),
        migrations.AddConstraint(
            model_name='clusterstoragemount',
            constraint=models.UniqueConstraint(fields=('cluster_storage', 'node'), name='unique_cluster_storage_mount_scope', nulls_distinct=False),
        ),
        migrations.AddIndex(
            model_name='clusterstoragenodestate',
            index=models.Index(fields=['cluster_storage', 'present', 'active'], name='core_csnode_state_idx'),
        ),
        migrations.AddIndex(
            model_name='clusterstoragenodestate',
            index=models.Index(fields=['node', 'active'], name='core_csnode_active_idx'),
        ),
        migrations.AddConstraint(
            model_name='clusterstoragenodestate',
            constraint=models.UniqueConstraint(fields=('cluster_storage', 'node'), name='unique_cluster_storage_node_state'),
        ),
        migrations.AddIndex(
            model_name='clusterstoragevolumeobservation',
            index=models.Index(fields=['cluster_storage', 'observed_volume_generation'], name='core_csvol_generation_idx'),
        ),
        migrations.AddIndex(
            model_name='clusterstoragevolumeobservation',
            index=models.Index(fields=['vmid'], name='core_csvol_vmid_idx'),
        ),
        migrations.AddIndex(
            model_name='clusterstoragevolumeobservation',
            index=models.Index(fields=['content'], name='core_csvol_content_idx'),
        ),
        migrations.AddConstraint(
            model_name='clusterstoragevolumeobservation',
            constraint=models.UniqueConstraint(fields=('cluster_storage', 'node', 'volid'), name='unique_cluster_storage_volume_observation'),
        ),
        migrations.RunPython(backfill_storage_foundation, reverse_storage_foundation_backfill),
        migrations.AlterField(
            model_name='storagemount',
            name='mount_key',
            field=models.UUIDField(default=uuid.uuid4, editable=False, unique=True),
        ),
        migrations.AlterField(
            model_name='storagemount',
            name='storage_id',
            field=models.CharField(db_index=True, max_length=120),
        ),
        migrations.AddConstraint(
            model_name='storagemount',
            constraint=models.UniqueConstraint(condition=models.Q(('relative_path', ''), _negated=True), fields=('relative_path',), name='unique_storage_mount_path'),
        ),
    ]
