# Generated by Django 6.0.7 on 2026-07-19 13:51

import django.db.models.deletion
from django.db import migrations, models


def backfill_complete_volume_coverage(apps, schema_editor):
    ClusterStorageVolumeCoverage = apps.get_model("core", "ClusterStorageVolumeCoverage")
    StorageCatalogState = apps.get_model("core", "StorageCatalogState")

    for state in StorageCatalogState.objects.filter(
        volume_complete=True,
        volume_generation__isnull=False,
        volume_based_on_metadata_generation__isnull=False,
    ).iterator():
        if state.volume_based_on_metadata_generation != state.metadata_generation:
            continue
        definitions = state.cluster.storage_definitions.filter(present=True, disabled=False)
        for definition in definitions.iterator():
            common = {
                "cluster_storage_id": definition.pk,
                "volume_generation": state.volume_generation,
                "based_on_metadata_generation": state.volume_based_on_metadata_generation,
                "refreshed_at": state.volume_refreshed_at,
                "last_attempt_at": state.volume_last_attempt_at,
                "complete": True,
            }
            if definition.shared:
                ClusterStorageVolumeCoverage.objects.create(scope="shared", node=None, **common)
                continue
            nodes = definition.node_states.filter(present=True, active=True, enabled=True).values_list(
                "node", flat=True
            )
            ClusterStorageVolumeCoverage.objects.bulk_create(
                [
                    ClusterStorageVolumeCoverage(scope="node", node=node, **common)
                    for node in nodes
                ]
            )


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0018_storage_catalog_foundation'),
    ]

    operations = [
        migrations.CreateModel(
            name='ClusterStorageVolumeCoverage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('scope', models.CharField(choices=[('shared', 'Shared'), ('node', 'Node')], max_length=12)),
                ('node', models.CharField(blank=True, max_length=120, null=True)),
                ('volume_generation', models.UUIDField(blank=True, null=True)),
                ('based_on_metadata_generation', models.UUIDField(blank=True, null=True)),
                ('refreshed_at', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('last_attempt_at', models.DateTimeField(blank=True, null=True)),
                ('complete', models.BooleanField(default=False)),
                ('error_code', models.CharField(blank=True, max_length=64)),
                ('error_reason', models.CharField(blank=True, max_length=255)),
                ('cluster_storage', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='volume_coverages', to='core.clusterstorage')),
            ],
            options={
                'ordering': ['cluster_storage__cluster__key', 'cluster_storage__storage_id', 'node'],
                'indexes': [models.Index(fields=['cluster_storage', 'complete'], name='core_csvolcov_state_idx')],
                'constraints': [models.CheckConstraint(condition=models.Q(models.Q(('node__isnull', True), ('scope', 'shared')), models.Q(('node__isnull', False), ('scope', 'node')), _connector='OR'), name='storage_volume_coverage_scope_node'), models.UniqueConstraint(fields=('cluster_storage', 'node'), name='unique_storage_volume_coverage_scope', nulls_distinct=False)],
            },
        ),
        migrations.RunPython(backfill_complete_volume_coverage, migrations.RunPython.noop),
        migrations.RemoveField(
            model_name="storagecatalogstate",
            name="volume_based_on_metadata_generation",
        ),
        migrations.RemoveField(
            model_name="storagecatalogstate",
            name="volume_generation",
        ),
    ]
